linter:
  rules:
    avoid_void_async: true
    always_use_package_imports: true
    avoid_unused_constructor_parameters: true
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_assignments: true
    unnecessary_statements: true
    use_if_null_to_convert_nulls_to_bools: true
    unnecessary_this: true
    unnecessary_parenthesis: true
    prefer_const_constructors: true
    prefer_int_literals: true
    use_build_context_synchronously: false
    directives_ordering: true
    avoid_classes_with_only_static_members: false
    require_trailing_commas: false


analyzer:
  strong-mode:
    implicit-casts: true
  exclude:
    - /**/*.g.dart
    - /**/*.freezed.dart
    - /**l10n/*.dart
    - /**/app_localizations**.dart
    - /**/generated/**/*.dart
    - /**/generated/*.dart
  errors:
    invalid_annotation_target: ignore