name: petsly
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.18.2+1
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.10
  provider: ^6.0.1
  build_context: ^3.0.0
  freezed_annotation: ^1.1.0
  geolocator: ^8.1.1
  logger: ^1.1.0
  image_picker: ^0.8.4+11

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/petsly_logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: LexendDeca
      fonts:
        - asset: font/LexendDeca-Regular.ttf
  assets:
    - "assets/petsly_logo.png"


